### ISSUE TITLE
README: Overriding example

### ISSUE THREAD

**Issue by hsiW** [zeyla/tslint-config-enkel#1]
The example of overriding found in the readme will currently not work, to properly override the config you need to add your rules you'd like to change to like the following example.

**Example**
```json
{
  "extends": "tslint-config-enkel",
  "rules": {
    "indent": [true, "spaces", 4]
  }
}
```

**Comment by zeyla** [comment]
Closed by 9831a1d97efef06d1f86a721eb3901389287c8e6.
